requirement: 2
countdown: 20
spawn:
  world: "skywars"
  x: 25.5
  y: 138.0
  z: 1.5
  yaw: -180
  pitch: 0
arena:
  world: "skywars"
  points:
    - [ 59.5, 65.5, 23.5, -180.0, 0.0 ]
    - [ 39.5, 65.5, 23.5, -180.0, 0.0 ]
    - [ -23.5, 64.5, 9.5, -90.0, 0.0 ]